# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.20
_src_path: gh:oca/oca-addons-repo-template
ci: GitHub
convert_readme_fragments_to_markdown: false
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: true
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: false
odoo_test_flavor: Both
odoo_version: 14.0
org_name: Escodoo
org_slug: Escodoo
rebel_module_groups: []
repo_description: Custom Addons Repository for Client-specific Solution.
repo_name: Escodoo Custom Addons
repo_slug: escodoo-addons
repo_website: https://github.com/Escodoo/escodoo-addons
use_pyproject_toml: false
use_ruff: false

