#!/usr/bin/env python3
# Copyright 2026 Escodoo
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).
"""Regenerate ``data/ir_attachment_pre.xml`` from the binary folder.

Every picture in ``static/src/binary/ir_attachment/`` becomes a public
``ir.attachment`` whose xmlid is the file stem, so the pages reference it as
``/web/image/escodoo_website.<stem>``. The records are ``noupdate`` so an image
replaced from the website editor is not overwritten on upgrade.

Usage: tools/build_attachment_xml.py
"""

# A command line tool run by a developer, never imported by Odoo, so its report
# belongs on stdout rather than in the server log.
# pylint: disable=print-used

from pathlib import Path

MODULE = "escodoo_website"
BINARY_SUBPATH = "static/src/binary/ir_attachment"
MIMETYPES = {
    ".png": "image/png",
    ".jpg": "image/jpeg",
    ".jpeg": "image/jpeg",
    ".svg": "image/svg+xml",
    ".webp": "image/webp",
}

HEADER = """<?xml version="1.0" encoding="utf-8" ?>
<!-- Generated by tools/build_attachment_xml.py. Do not edit by hand. -->
<odoo noupdate="1">
"""
FOOTER = "</odoo>\n"

RECORD = """    <record id="{stem}" model="ir.attachment">
        <field name="name">{name}</field>
        <field name="mimetype">{mimetype}</field>
        <field
            name="datas"
            type="base64"
            file="{module}/{subpath}/{name}"
        />
        <field name="public" eval="True" />
    </record>
"""


def main():
    module_dir = Path(__file__).resolve().parent.parent
    binary_dir = module_dir / BINARY_SUBPATH
    target = module_dir / "data/ir_attachment_pre.xml"

    records = []
    for path in sorted(binary_dir.iterdir()):
        mimetype = MIMETYPES.get(path.suffix.lower())
        if not mimetype:
            continue
        records.append(
            RECORD.format(
                stem=path.stem,
                name=path.name,
                mimetype=mimetype,
                module=MODULE,
                subpath=BINARY_SUBPATH,
            )
        )

    target.write_text(HEADER + "".join(records) + FOOTER, encoding="utf-8")
    print(f"wrote {len(records)} attachments to {target.relative_to(module_dir)}")


if __name__ == "__main__":
    main()
