# Copyright 2026 Escodoo
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).
{
    "name": "Escodoo Website",
    "summary": "Public website for Escodoo: Odoo Community, OCA and Brazilian "
    "fiscal localisation services",
    "version": "18.0.1.0.0",
    "category": "Website",
    "author": "Escodoo",
    "website": "https://github.com/Escodoo/escodoo-addons",
    "license": "AGPL-3",
    "development_status": "Beta",
    "maintainers": ["marcelsavegnago"],
    "depends": [
        "website",
        "website_crm",
        "website_mass_mailing",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/ir_attachment_pre.xml",
        "data/website.xml",
        "data/escodoo_website_feature_category.xml",
        "data/escodoo_website_feature_segment.xml",
        "data/escodoo.website.feature.csv",
        "views/escodoo_website_feature_views.xml",
        "report/escodoo_website_feature_report.xml",
        "data/website_view_snippets.xml",
        "data/website_view_home.xml",
        "data/website_view_editions.xml",
        "data/website_view_oca.xml",
        "data/website_view_feature_map.xml",
        "data/website_view_investment.xml",
        "data/website_view_sovereignty.xml",
        "data/website_view_odoo.xml",
        "data/website_view_advisor.xml",
        "data/website_view_solutions.xml",
        "data/website_view_services.xml",
        "data/website_view_segments.xml",
        "data/website_view_cases.xml",
        "data/website_view_company.xml",
        "data/website_view_conversion.xml",
        "data/website_templates.xml",
        "data/website_page.xml",
        "data/website_menu.xml",
        "data/website_theme_apply.xml",
    ],
    "assets": {
        "web.assets_frontend": [
            "escodoo_website/static/src/scss/escodoo_website.scss",
            "escodoo_website/static/src/js/feature_table.esm.js",
        ],
    },
    "installable": True,
    "post_init_hook": "post_init_hook",
}
